### ISSUE TITLE
AttributeError: 'module' object has no attribute 'exc_info'

### ISSUE THREAD

**Issue by sirmax123** [troublegum/micropyserver#1]
Env details:
System: ESP32
```
>>> print(sys.version_info)
(3, 4, 0)
```
```
MicroPython v1.11 on 2019-05-29; ESP32 module with ESP32
Type "help()" for more information.
```

According to the docs
https://docs.micropython.org/en/latest/library/sys.html another methid should be used

Original traceback
```
Traceback (most recent call last):
  File "micropyserver.py", line 66, in start
  File "micropyserver.py", line 114, in internal_error
AttributeError: 'module' object has no attribute 'exc_info'
```

**Comment by troublegum** [comment]
Fixed
